### ISSUE TITLE
the socket problem

### ISSUE THREAD

**Issue by TuoJAM** [CrazyHer/TempleRun#1]
how to use the socket to connect to tools set provided by teacher?(maybe your teacher don't supply.

**Comment by CrazyHer** [comment]
Run the unity project. It will listen socket on localhost:2333 waiting for the ./Kinect project to connect. It receives control commands from the socket.

Plug in your kinect2, install driver and run./Kinect project. It will connect the kinect2 device and get bones data and send control commands via socket that connected to unity project.

Email me if you still have any questions.
herui@mail.sdu.edu.cn
